[master]
main_page = "docs/pages/main-page.dox"
additional_pages = ["docs/pages/python-additional-info.md", "docs/pages/so3-minjerk.md"]
src_folder = "src"

['v0.16.1']
main_page = "docs/pages/main-page.dox"
additional_pages = ["docs/pages/python-additional-info.md", "docs/pages/so3-minjerk.md"]
src_folder = "src"

['v0.15.0']
main_page = "docs/pages/main-page.dox"
additional_pages = ["docs/pages/python-additional-info.md", "docs/pages/so3-minjerk.md"]
src_folder = "src"

['v0.14.1']
main_page = "docs/pages/main-page.dox"
additional_pages = ["docs/pages/python-additional-info.md", "docs/pages/so3-minjerk.md"]
src_folder = "src"

['v0.13.0']
main_page = "docs/pages/main-page.dox"
additional_pages = ["docs/pages/python-additional-info.md"]
src_folder = "src"

# ['v0.12.0']
# main_page = "docs/pages/main-page.dox"
# additional_pages = ["docs/pages/python-additional-info.md"]
# src_folder = "src"

# ['v0.11.1']
# main_page = "docs/pages/main-page.dox"
# additional_pages = ["docs/pages/python-additional-info.md"]
# src_folder = "src"

# ['v0.10.0']
# main_page = "docs/pages/main-page.dox"
# additional_pages = ["docs/pages/python-additional-info.md"]
# src_folder = "src"

# ['v0.9.0']
# main_page = "docs/pages/main-page.dox"
# additional_pages = ["docs/pages/python-additional-info.md"]
# src_folder = "src"

# ['v0.8.0']
# main_page = "docs/pages/main-page.dox"
# additional_pages = ["docs/pages/python-additional-info.md"]
# src_folder = "src"

# ['v0.7.0']
# main_page = "docs/pages/main-page.dox"
# additional_pages = ["docs/pages/python-additional-info.md"]
# src_folder = "src"

# ['v0.6.0']
# main_page = "docs/pages/main-page.dox"
# additional_pages = ["docs/pages/python-additional-info.md"]
# src_folder = "src"

# ['v0.5.0']
# main_page = "docs/pages/main-page.dox"
# additional_pages = ["docs/pages/python-additional-info.md"]
# src_folder = "src"

# ['v0.4.0']
# main_page = "docs/pages/main-page.dox"
# src_folder = "src"

# ['v0.3.0']
# main_page = "docs/pages/main-page.dox"
# src_folder = "src"

# ['v0.2.0']
# main_page = "docs/pages/main-page.dox"
# src_folder = "src"

# ['v0.1.1']
# main_page = "README.md"
# src_folder = "src"
