name: Update the labeler.yml file

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'


jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update the labeler file
        run: |
          cd ./.ci
          python3 generate-labeler-file.py
      - name: Check for modified files
        id: git-check
        run: |
          echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Create Pull Request
        id: cpr
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Automatic update of latest releases versions
          committer: GitHub <noreply@github.com>
          branch: automatic-update-labeler-file
          delete-branch: true
          title: 'Automatic update `.github/labeler.yml` file :rocket:'
          body: |
             This automatic PR updates the content of `.github/labeler.yml` accordingly to repository structure.
             This PR is triggered only if a new component has been added in the `./src` folder.

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
